### ISSUE TITLE
Flatten nested media queries

### ISSUE THREAD

**Issue by rtsao** [rtsao/scope-styles#11]
``` javascript
{
  foo: {
    '@media (max-width: 600px)': {
      '@media (min-width: 200px)': {
         color: 'blue'
       }
    }
  }
}
```

``` css
@media (max-width: 600px) and (min-width: 200px) {
  .foo {
    color: blue
  }
}
```

The utility of this seems dubious at the moment, but maybe this is worth implementing?
