### ISSUE TITLE
Support fallbacks

### ISSUE THREAD

**Issue by rtsao** [rtsao/scope-styles#16]
``` js
{
  foo: {
    color: [
      'rgba(0, 0, 0, 0.5)',
      '#ccc'
    ]
  }
}
```

``` css
.foo {
    color: rgba(0, 0, 0, 0.5);
    color: #ccc
}
```
