### ISSUE TITLE
Better/more flexible handling of nesting?

### ISSUE THREAD

**Issue by rtsao** [rtsao/scope-styles#2]
Deep nesting is an anti-pattern but I suppose there's a valid use case for something like below:

styles object

``` javascript
{
  foo: {
    '@media (max-width: 600px)': {
      ':after': {
         color: 'blue'
       }
    }
  }
}
```

expected css (unscoped)

``` css
@media (max-width: 600px) {
  .foo:after {
    color: blue
  }
}
```

**Comment by rtsao** [comment]
Another potential use case:

``` javascript
{
  '@media (max-width: 600px)': {
    foo: {
      color: 'blue'
    },
    bar: {
      color: 'green'
    },
  }
}
```

expected css (unscoped)

``` css
@media (max-width: 600px) {
  .foo {
    color: blue
  }
  .bar {
    color: green
  }
}
```
